version: '3'
services:
  # ...... Other configs ......
  database:
    image: mongo:latest

    container_name: mongo-note-app

    # environment:
    #   - MONGO_INITDB_DATABASE = note-app
    #   - MONGO_INITDB_ROOT_USERNAME = ${USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD = mongoroot
    env_file: .docker.env

    volumes:
      - .init-mongo.js:/docker-entrypoint-initdb.d/init-mongo:ro
      - ./mongo-volume:/data/db

    ports:
      - '27017-27019:27017-27019'

  # ...... Other configs ...........
  